apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-app
  namespace: prod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloud-devops-app
  template:
    metadata:
      labels:
        app: cloud-devops-app
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Chart.Name }}
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: {{ .Chart.Name }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Chart.Name }}
#     spec:
#       containers:
#         - name: {{ .Chart.Name }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - containerPort: 8080
#           {{- if .Values.secrets.mongo.enabled }}
#           env:
#             - name: MONGO_URI
#               valueFrom:
#                 secretKeyRef:
#                   name: mongo-secret
#                   key: uri
#           {{- end }}

