apiVersion: v1
kind: Service
metadata:
  name: cloud-devops-app
  namespace: prod
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cloud-devops-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Chart.Name }}
# spec:
#   type: {{ .Values.service.type }}
#   selector:
#     app: {{ .Chart.Name }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.targetPort }}

