name: CD - Deploy with ArgoCD

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'prod'
        type: choice
        options: [prod, nonprod]

env:
  TF_DIR: terraform
  AWS_REGION: eu-north-1

jobs:
  deploy-process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Update Kubeconfig
        run: |
          cd $TF_DIR
          terraform init -input=false
          CLUSTER_NAME=$(terraform output -raw eks_cluster_name 2>/dev/null || echo "${{ github.event.inputs.env }}-eks")
          aws eks update-kubeconfig --name "$CLUSTER_NAME" --region ${{ env.AWS_REGION }}

      - name: Apply ArgoCD App (Dynamic Versioning)
        run: |
          cd $TF_DIR
          ECR_URL=$(terraform output -raw ecr_repository_url)
          
          # catch the current tag to use it
          CURRENT_TAG=${GITHUB_SHA::7}
          
          cat <<EOF > argocd-app.yaml
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: cloud-devops-app
            namespace: prod
          spec:
            project: default
            source:
              repoURL: https://github.com/RadwaMohammedKamal/CloudDevOps.git
              targetRevision: HEAD
              path: helm-charts
              helm:
                parameters:
                  - name: "image.repository"
                    value: "$ECR_URL"
                  - name: "image.tag"
                    value: "$CURRENT_TAG" 
            destination:
              server: https://kubernetes.default.svc
              namespace: prod
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
          EOF
          kubectl apply -f argocd-app.yaml

      - name: Print Final Links
        run: |
          sleep 10
          NLB_DNS=$(kubectl get svc -n prod -l app.kubernetes.io/name=ingress-nginx -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}')
          echo "=========================================================="
          echo "ðŸš€ Your Environment is Ready with Version: ${GITHUB_SHA::7}"
          echo "ðŸ”— App URL: http://$NLB_DNS/app"
          echo "ðŸ”§ ArgoCD: http://$NLB_DNS/argocd"
          echo "ðŸ“Š SonarQube: http://$NLB_DNS/sonarqube"
          echo "=========================================================="


